import SwiftUI
import SwiftData
import FoundationModels

struct AISummaryCard: View {
    @Environment(\.modelContext) private var modelContext

    let viewModel: TripSummaryViewModel
    let trip: Trip

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            header

            VStack(alignment: .leading, spacing: 8) {
                content

                if viewModel.summary != nil && viewModel.wasGeneratedByAI {
                    Text("Generated by Foundation Models · On-device")
                        .font(.caption2)
                        .foregroundStyle(.secondary)
                }
            }
            .frame(maxWidth: .infinity, alignment: .leading)
            .padding(12)
        }
        .clipShape(RoundedRectangle(cornerRadius: 12))
        .overlay(
            RoundedRectangle(cornerRadius: 12)
                .stroke(Color.blue.opacity(0.2), lineWidth: 1)
        )
    }

    private var header: some View {
        HStack {
            Image(systemName: "sparkles")
                .foregroundStyle(.white)

            Text("AI TRIP SUMMARY")
                .font(.caption)
                .fontWeight(.semibold)
                .foregroundStyle(.white)

            Spacer()
        }
        .padding(10)
        .background(
            LinearGradient(
                colors: [.blue, .blue.opacity(0.6)],
                startPoint: .leading,
                endPoint: .trailing
            )
        )
    }

    @ViewBuilder
    private var content: some View {
        if viewModel.isGenerating {
            HStack(spacing: 8) {
                ProgressView()
                Text("Generating summary…")
                    .foregroundStyle(.secondary)
                    .font(.caption)
            }
        } else if let errorMessage = viewModel.errorMessage {
            VStack(alignment: .leading, spacing: 8) {
                Text(errorMessage)
                    .font(.caption)
                    .foregroundStyle(.red)

                Button("Retry") {
                    Task { await viewModel.retry(for: trip, context: modelContext) }
                }
                .font(.caption)
            }
        } else if let summary = viewModel.summary {
            VStack(alignment: .leading, spacing: 8) {
                Text(summary.summary)
                    .font(.callout)

                if !summary.highlights.isEmpty {
                    VStack(alignment: .leading, spacing: 4) {
                        ForEach(summary.highlights, id: \.self) { highlight in
                            Label(highlight, systemImage: "star.fill")
                                .font(.caption)
                                .foregroundStyle(.secondary)
                        }
                    }
                }
            }
        } else {
            Text("AI features require Apple Intelligence.")
                .font(.caption)
                .foregroundStyle(.secondary)
        }
    }
}
